In [232]:
## load the dataset
import pandas as pd
import numpy as np
data = pd.read_csv("C://Users//DELL//PycharmProjects//PythonProject_practice_2025//Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [233]:
## preprocess the data
# drop irrelevant columns
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis = 1)
data.head(10)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [234]:
#encode categorical variables - Gender
from sklearn.preprocessing import LabelEncoder
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])
data.head(10)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
5,645,Spain,1,44,8,113755.78,2,1,0,149756.71,1
6,822,France,1,50,7,0.00,2,1,1,10062.80,0
7,376,Germany,0,29,4,115046.74,4,1,0,119346.88,1
8,501,France,1,44,4,142051.07,2,0,1,74940.50,0
9,684,France,1,27,2,134603.88,1,1,1,71725.73,0

In [235]:
# one hot encoding for Geography Column
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder(categories='auto', sparse_output=False)
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [236]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [237]:
geo_encoder_df = pd.DataFrame(geo_encoder, columns = onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoder_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [238]:
## combine one hot encoder columns with the original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoder_df], axis =1)
data.head(10)

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
5,645,1,44,8,113755.78,2,1,0,149756.71,1,0.0,0.0,1.0
6,822,1,50,7,0.00,2,1,1,10062.80,0,1.0,0.0,0.0
7,376,0,29,4,115046.74,4,1,0,119346.88,1,0.0,1.0,0.0
8,501,1,44,4,142051.07,2,0,1,74940.50,0,1.0,0.0,0.0
9,684,1,27,2,134603.88,1,1,1,71725.73,0,1.0,0.0,0.0

In [239]:
## Save the encoders and scaler in the pickle file
import pickle
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

In [240]:
# divide the dataset into independent and dependent feature
X = pd.get_dummies(data.drop('Exited', axis=1), drop_first=True)
y = data['Exited']

## split the data in training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
## Scale these features
from sklearn.preprocessing import StandardScaler, LabelEncoder
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [241]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [242]:
with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [243]:
##ANN implementation
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import datetime

In [244]:
X_train.shape[1]

12

In [245]:
## Build our ANN model

model = Sequential([
    Dense(64, activation = 'relu', input_shape = (X_train.shape[1],)), ## HL1 connected with input layer
    Dense(32, activation = 'relu'), ## HL2
    Dense(1, activation = 'sigmoid') ## output layer
])

In [246]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_15 (Dense)            (None, 64)                832

 dense_16 (Dense)            (None, 32)                2080

 dense_17 (Dense)            (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [247]:
#optimizer and loss function as per your requirement

opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()

In [248]:
## compile the model
# our own initialization
model.compile(optimizer = opt, loss = loss, metrics=['accuracy'])

#Initialise default
#model.compile(optimizer = "adam", loss = 'binary_crossentropy', metrics=['accuracy'])

In [249]:
## Set u[ the Tensorboard

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

In [250]:
## setup the Tensorboard

from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

tensorflow_callback = TensorBoard(log_dir=log_dir, histogram_freq = 1)

In [251]:
## setup early stopping

early_stopping_callback = EarlyStopping(monitor = 'val_loss', patience = 10, restore_best_weights = True)

In [252]:
## Training the model

history = model.fit(
    X_train, y_train, validation_data = (X_test, y_test), epochs = 100,
    callbacks = [tensorflow_callback, early_stopping_callback]
)

Epoch 1/100
250/250 [==============================] - 3s 7ms/step - loss: 0.3978 - accuracy: 0.8313 - val_loss: 0.3557 - val_accuracy: 0.8555
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3551 - accuracy: 0.8547 - val_loss: 0.3449 - val_accuracy: 0.8585
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3461 - accuracy: 0.8566 - val_loss: 0.3548 - val_accuracy: 0.8590
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3431 - accuracy: 0.8611 - val_loss: 0.3458 - val_accuracy: 0.8625
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3394 - accuracy: 0.8639 - val_loss: 0.3459 - val_accuracy: 0.8585
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3381 - accuracy: 0.8612 - val_loss: 0.3383 - val_accuracy: 0.8575
Epoch 7/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3346 - accuracy: 0.8649 - val_loss: 0.3390 - val_accuracy: 0.8590
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3341 - accuracy: 0.8645 - val_loss: 0.3384 - val_accuracy: 0.8605
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3325 - accuracy: 0.8649 - val_loss: 0.3328 - val_accuracy: 0.8645
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3290 - accuracy: 0.8640 - val_loss: 0.3406 - val_accuracy: 0.8610
Epoch 11/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3271 - accuracy: 0.8671 - val_loss: 0.3359 - val_accuracy: 0.8615
Epoch 12/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3232 - accuracy: 0.8671 - val_loss: 0.3433 - val_accuracy: 0.8645
Epoch 13/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3238 - accuracy: 0.8664 - val_loss: 0.3392 - val_accuracy: 0.8635
Epoch 14/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3187 - accuracy: 0.8680 - val_loss: 0.3412 - val_accuracy: 0.8590
Epoch 15/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3190 - accuracy: 0.8694 - val_loss: 0.3389 - val_accuracy: 0.8655
Epoch 16/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3153 - accuracy: 0.8708 - val_loss: 0.3412 - val_accuracy: 0.8635
Epoch 17/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3109 - accuracy: 0.8695 - val_loss: 0.3599 - val_accuracy: 0.8635
Epoch 18/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3087 - accuracy: 0.8725 - val_loss: 0.3536 - val_accuracy: 0.8600
Epoch 19/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3103 - accuracy: 0.8731 - val_loss: 0.3583 - val_accuracy: 0.8645

In [253]:
#model.save("model.keras")
model.save("model.h5")

C:\Users\DELL\PyCharmMiscProject\.venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [254]:
## load tensorboard extention

%load_ext tensorboard
#%reload_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [255]:
%reload_ext tensorboard
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 13516), started 1 day, 1:28:57 ago. (Use '!kill 13516' to kill it.)

In [256]:
# you can run the comand --> tensorboard --logdir logs/fit on terminal ir will open in a browser window

In [257]:
## loading the pickle file - trained model, Scaler, OHE
from tensorflow.keras.models import load_model
#model = load_model('model.keras')
model = load_model('model.h5')

# loading Encoder and Scaler

with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender = pickle.load(file)

with open('onehot_encoder_geo.pkl', 'rb') as file:
    onehot_encoder_geo.pkl = pickle.load(file)

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

# Checking the model with a example input data

In [258]:


input_data = {
    'CreditScore':600,
    'Geography':'France',
    'Gender':'Male',
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000
}

In [259]:
# one hot encoding for 'Geography'

geo_encoded = onehot_encoder_geo.transform([[input_data['Geography']]])
geo_encoded_df = pd.DataFrame(geo_encoded, columns = onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

C:\Users\DELL\PyCharmMiscProject\.venv\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [260]:
# since input is in key:value we convert into dataframe for concatination
input_df = pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [261]:
# Categorical encoding for 'Gender'

input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [262]:
#combine one-hot encoded columns with input data

input_data = pd.concat([input_df.drop('Geography', axis = 1), geo_encoded_df], axis =1)
input_data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [263]:
## scaling the input data
input_scaled = scaler.transform(input_data)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [264]:
## predict Churn - if the person is gonna exit(leave) the bank or not
prediction = model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 174ms/step

array([[0.05660511]], dtype=float32)

In [265]:
preiction_probability = prediction[0][0]
preiction_probability

0.056605108

In [266]:

if preiction_probability > 0.5:
    print("-" * 40)
    print("The customer is likely to churn" )
    print("-" * 40)
else:
    print("-" * 40)
    print("The customer is not likely to churn")
    print("-" * 40)

print(f"Probability: {preiction_probability:.3f}")

----------------------------------------
The customer is not likely to churn
----------------------------------------
Probability: 0.057